bygg knada-jupyterhub nå base-image oppdateres

diff --git a/.github/workflows/jupyter.yaml b/.github/workflows/jupyter.yaml
--- a/.github/workflows/jupyter.yaml
+++ b/.github/workflows/jupyter.yaml
@@ -8,6 +8,8 @@ on:
       - .github/workflows/jupyter.yaml
       - jupyter/Dockerfile
   workflow_dispatch:
+  schedule:
+    - cron: '0 7 * * *'
 
 env:
   IMAGE: europe-west1-docker.pkg.dev/knada-gcp/jupyterhub/knada-jupyterhub
@@ -38,6 +40,24 @@ jobs:
           registry: europe-west1-docker.pkg.dev
           username: oauth2accesstoken
           password: ${{ steps.auth.outputs.access_token }}
-      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
-      - run: docker build -t $IMAGE:$TAG-${{ matrix.version }} -f jupyter/Dockerfile --build-arg python_version=${{ matrix.version }} .
-      - run: docker push $IMAGE:$TAG-${{ matrix.version }}
+      - run: |
+          knada=$(gcloud artifacts docker images list europe-west1-docker.pkg.dev/knada-gcp/knada/jupyter --include-tags --filter TAGS:-{{ matrix.version }} --sort-by=~Update_Time --limit=1 --format=json)
+
+          python3 compare_tags.py "$knada" "python-${{ matrix.version }}"
+          out=$?
+          if [ $out -eq 100 ]
+          then
+              echo "outdated=true" >> $GITHUB_ENV
+          elif [ $out != 0 ]
+          then
+              echo "up to date"
+          else
+              echo "error"
+          fi
+
+      - if: ${{ env.outdated }} == "true" || contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
+        run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
+      - if: ${{ env.outdated }} == "true" || contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
+        run: docker build -t $IMAGE:$TAG-${{ matrix.version }} -f jupyter/Dockerfile --build-arg python_version=${{ matrix.version }} .
+      - if: ${{ env.outdated }} == "true" || contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
+        run: docker push $IMAGE:$TAG-${{ matrix.version }}
